# Day-2 Practing Numpy

In [2]:
import numpy as np

### numpy array operation

#### Indexing and slicing

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing:",arr[1:9])
print("Step Slicing:",arr[1:9:2])
print("Negative slicing:",arr[-5:-3])

Basic slicing: [2 3 4 5 6 7 8 9]
Step Slicing: [2 4 6 8]
Negative slicing: [6 7]


#### 2-D slicing

In [4]:
arr_2d=np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]
     ])
print(f"Specific element:{arr_2d[1,0]}")
print(f"Entire Row element:{arr_2d[1]}")
print(f"Entire column element:{arr_2d[:,2]}")

Specific element:4
Entire Row element:[4 5 6]
Entire column element:[3 6 9]


### Sorting

In [5]:
Unsorted=np.array([1,0,3,6,9,5,21,4,6])
print("Sorted array are:",np.sort(Unsorted))
arr_2d_unsorted=np.array([[3,1,2],[2,3,1],[1,3,2]])
print("Sorted by Columns:\n",np.sort(arr_2d_unsorted,axis=0))
print("Sorted by Rows:\n",np.sort(arr_2d_unsorted,axis=1))

Sorted array are: [ 0  1  3  4  5  6  6  9 21]
Sorted by Columns:
 [[1 1 1]
 [2 3 2]
 [3 3 2]]
Sorted by Rows:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


### Filter

In [6]:
number = np.arange(1,11)
print(f"Original array:{number}")
even=number[number%2==0]
print(f"Even Number:{even}")

Original array:[ 1  2  3  4  5  6  7  8  9 10]
Even Number:[ 2  4  6  8 10]


### Filter with mask

In [12]:
mask= number > 5
print(f"Number is greater than 5 {mask}")
print(f"Number is greater than 5 {number[mask]}")

Number is greater than 5 [False False False False False  True  True  True  True  True]
Number is greater than 5 [ 6  7  8  9 10]


### Fancing indexing and np.where()

In [15]:
indices=[0,2,4]
print(number[indices])
Where_result=np.where(number>5)
print("By using where function:",Where_result)
Where_result=np.where(number>5)
print("By using where function:",number[Where_result])

[1 3 5]
By using where function: (array([5, 6, 7, 8, 9]),)
By using where function: [ 6  7  8  9 10]


### Condition

In [16]:
condition_result=np.where(number>5,True,False)
print(condition_result)

[False False False False False  True  True  True  True  True]


### Adding and removing data

In [21]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=arr1+arr2
print(combined)
combined1=np.concatenate((arr1,arr2))
print(combined1)

[5 7 9]
[1 2 3 4 5 6]


#### array compactibility

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
print(a.shape == b.shape and b.shape == c.shape and c.shape == a.shape)

False


### Vstack and hstack

In [33]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
with_new_row=np.vstack((original,new_row))
print("New row:\n",with_new_row)
new_col=np.array([[5],[6]])
with_new_col=np.hstack((original,new_col))
print("New row:\n",with_new_col)

New row:
 [[1 2]
 [3 4]
 [5 6]]
New row:
 [[1 2 5]
 [3 4 6]]


#### array deletion

In [34]:
arr=np.array([1,2,3,4,5,6,7,8,9])
deleted=np.delete(arr,3)
print(deleted)

[1 2 3 5 6 7 8 9]


# That all for today